server:
  port: 8089
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/duser?useSSL=false
    username: root
    password: 122964
    driver-class-name: com.mysql.jdbc.Driver
  elasticsearch:
    rest:
      uris: http://192.168.153.128:9200

logging:
  level:
    cn.itcast: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: cn.itcast.hotel.pojo